// types/simulation/gros-mots.ts

export const PROFANITY_LIST2 = [
    "merde",
    "putain",
    "oh la vache",
    "oh purée",
    "fait chier",
    "sa mère",
    "tu fais chier",
    "j'en ai marre",
    "ras-le-bol",
    "ras-la-casquette",
    "débile",
    "imbécile",
    "crétin",
    "à la con",
    "rien à dire",
    "emmerde",
    "casse-toi",
    "barre-toi",
    "rien dans le crâne",
    "enculer",
    "enculé",
    "foutre",
    "abruti",
    "con", 
    "connard", 
    "connasse",
    "sale con", 
    "vieux con", 
    "jeune con", 
    "gros con",
    "ta gueule",
    "ferme-la",
    "salope",
    "salaud",
    "ras-le-cul",
    "je m'en fous",
    "je m'en fiche",
    "rien à carrer",
    "bâtard",
    "fils de chien",
    "fils de pute",
    "trou du cul",
    "trou de balle"
  ];

export const PROFANITY_LIST = [
    "merde",
    "putain",
  ];